name: .NET Build, Test, and Publish

on:
  push:
    branches: [ "main" ]
    tags:     [ 'v*' ]
  pull_request:
    branches: [ "main" ]

jobs:
#──────────────────────────────────────────────────────────────────────────────
# Build & test on both SDKs
#──────────────────────────────────────────────────────────────────────────────
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ['8.0.x', '9.0.x']             # add more if you like
    name: Build & Test (.NET ${{ matrix.sdk }})

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.sdk }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.sdk }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: |
        if [[ "${{ matrix.sdk }}" == "8.0.x" ]]; then
          dotnet build --no-restore --configuration Release \
                       -p:TargetFramework=net8.0        # 👈 build only net8
        else
          dotnet build --no-restore --configuration Release
        fi

    - name: Test
      run: |
        if [[ "${{ matrix.sdk }}" == "8.0.x" ]]; then
          dotnet test --no-build --configuration Release \
                      --framework net8.0 --verbosity normal
        else
          dotnet test --no-build --configuration Release --verbosity normal
        fi

#──────────────────────────────────────────────────────────────────────────────
# Publish NuGet package (runs once, only on tag push)
#──────────────────────────────────────────────────────────────────────────────
  publish-to-nuget:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Create NuGet package
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        dotnet pack src/OatIM.DeltaCompression.csproj \
                    --configuration Release \
                    /p:Version=$VERSION \
                    --output ./nupkg

    - name: Publish to NuGet.org
      run: dotnet nuget push "./nupkg/*.nupkg" \
              --api-key "${{ secrets.NUGET_API_KEY }}" \
              --source "https://api.nuget.org/v3/index.json"
