name: .NET Build, Test, and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.target-framework }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # This matrix now explicitly defines the SDK version for each target framework,
        # avoiding invalid expression syntax.
        include:
          - target-framework: 'net8.0'
            sdk-version: '8.0.x'
          - target-framework: 'net9.0'
            sdk-version: '9.0.x'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.sdk-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.sdk-version }}

    - name: Restore dependencies
      # We explicitly tell restore which framework to target.
      run: dotnet restore --framework ${{ matrix.target-framework }}

    - name: Build
      # We build only for the specific framework of this matrix job.
      run: dotnet build --no-restore --configuration Release --framework ${{ matrix.target-framework }}

    - name: Test
      # We test only for the specific framework of this matrix job.
      run: dotnet test --no-build --verbosity normal --configuration Release --framework ${{ matrix.target-framework }}

  publish-to-nuget:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Use the highest supported SDK for packing, as it can handle all target frameworks.
        dotnet-version: '9.0.x'
    - name: Create NuGet Package
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        dotnet pack src/Oat.IO.DeltaCompression.csproj --configuration Release --output ./nupkg /p:Version=$VERSION
    - name: Publish to NuGet.org
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json"

